api_version = "2025-07"

[[extensions]]
name = "Health Roadmap"
handle = "health-tool-page"
uid = "21fd403a-f8df-ff30-aaba-cc25ddd73d95a5a0a2f6"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/HealthToolPage.tsx"
target = "customer-account.page.render"

[extensions.capabilities]
network_access = true
