api_version = "2025-07"

[[extensions]]
name = "health-roadmap-link"
handle = "health-roadmap-link"
uid = "335ffdaa-b0a8-23b7-6e72-57e2821eada2ad16d50a"
type = "ui_extension"

[extensions.settings]
  [[extensions.settings.fields]]
  key = "roadmap_url"
  type = "single_line_text_field"
  name = "Roadmap page"
  description = "Select the health roadmap page"

[[extensions.targeting]]
module = "./src/ProfileLinkBlock.ts"
target = "customer-account.profile.block.render"

[[extensions.targeting]]
module = "./src/OrderLinkBlock.ts"
target = "customer-account.order-index.block.render"
